package com.peihou.waterpurifer.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.peihou.waterpurifer.pojo.Equipment;
import com.peihou.waterpurifer.pojo.Packages;
import com.peihou.waterpurifer.pojo.Packageschild;
import com.peihou.waterpurifer.pojo.TimerTask;

import com.peihou.waterpurifer.database.dao.EquipmentDao;
import com.peihou.waterpurifer.database.dao.PackagesDao;
import com.peihou.waterpurifer.database.dao.PackageschildDao;
import com.peihou.waterpurifer.database.dao.TimerTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig equipmentDaoConfig;
    private final DaoConfig packagesDaoConfig;
    private final DaoConfig packageschildDaoConfig;
    private final DaoConfig timerTaskDaoConfig;

    private final EquipmentDao equipmentDao;
    private final PackagesDao packagesDao;
    private final PackageschildDao packageschildDao;
    private final TimerTaskDao timerTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        equipmentDaoConfig = daoConfigMap.get(EquipmentDao.class).clone();
        equipmentDaoConfig.initIdentityScope(type);

        packagesDaoConfig = daoConfigMap.get(PackagesDao.class).clone();
        packagesDaoConfig.initIdentityScope(type);

        packageschildDaoConfig = daoConfigMap.get(PackageschildDao.class).clone();
        packageschildDaoConfig.initIdentityScope(type);

        timerTaskDaoConfig = daoConfigMap.get(TimerTaskDao.class).clone();
        timerTaskDaoConfig.initIdentityScope(type);

        equipmentDao = new EquipmentDao(equipmentDaoConfig, this);
        packagesDao = new PackagesDao(packagesDaoConfig, this);
        packageschildDao = new PackageschildDao(packageschildDaoConfig, this);
        timerTaskDao = new TimerTaskDao(timerTaskDaoConfig, this);

        registerDao(Equipment.class, equipmentDao);
        registerDao(Packages.class, packagesDao);
        registerDao(Packageschild.class, packageschildDao);
        registerDao(TimerTask.class, timerTaskDao);
    }
    
    public void clear() {
        equipmentDaoConfig.clearIdentityScope();
        packagesDaoConfig.clearIdentityScope();
        packageschildDaoConfig.clearIdentityScope();
        timerTaskDaoConfig.clearIdentityScope();
    }

    public EquipmentDao getEquipmentDao() {
        return equipmentDao;
    }

    public PackagesDao getPackagesDao() {
        return packagesDao;
    }

    public PackageschildDao getPackageschildDao() {
        return packageschildDao;
    }

    public TimerTaskDao getTimerTaskDao() {
        return timerTaskDao;
    }

}
